version: '3.7'

services:

  booking-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/booapp-db"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: "com.mysql.jdbc.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL5Dialect"

  db:
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: booapp-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

